[book]
title = "HackFest '26"
authors = ["SREENIDHI Institute of Science and Technology"]
language = "en"

[output.html]
default-theme = "hackfest"
preferred-dark-theme = "hackfest"
additional-js = ["theme/plexus-background.js"]